services:
  app:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - postgres
    environment:
      DB_HOST: "postgres_container"
      DB_PORT: "5432"
      DB_NAME: "warehouse"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-warehouse}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data/pgdata
    networks:
      - postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
